from opentelemetry import metrics

# Get a meter for the agentdist library
# The meter provider is configured globally by the application using this library
meter = metrics.get_meter("agentdist")

# Counter: Tracks the number of tasks executed
TASK_EXECUTION_COUNT = meter.create_counter(
    name="agentdist.task.execution_count",
    description="The number of tasks executed by the orchestrator",
    unit="{task}",
)

# Histogram: Tracks how long tasks take to complete
TASK_EXECUTION_DURATION = meter.create_histogram(
    name="agentdist.task.execution_duration",
    description="The duration of task execution in seconds",
    unit="s",
)

# Histogram: Duration of environment setup (e.g., container start)
TASK_ENV_SETUP_DURATION = meter.create_histogram(
    name="agentdist.task.env_setup_duration",
    description="Duration of environment setup for a task",
    unit="s",
)

# Histogram: Duration of copying artifacts (inputs/outputs)
TASK_ARTIFACT_COPY_DURATION = meter.create_histogram(
    name="agentdist.task.artifact_copy_duration",
    description="Duration of copying artifacts for a task",
    unit="s",
)

# Histogram: Duration of the actual agent/UDF execution
TASK_AGENT_RUN_DURATION = meter.create_histogram(
    name="agentdist.task.agent_run_duration",
    description="Duration of the actual agent execution",
    unit="s",
)

#Histogram: Duration of the actual task setup time
TASK_SETUP_DURATION = meter.create_histogram(
    name="agentdist.task.task_setup_duration",
    description="Duration of the task setup time",
    unit="s",
)

# UpDownCounter: Number of tasks currently running
ACTIVE_TASKS = meter.create_up_down_counter(
    name="agentdist.orchestrator.active_tasks",
    description="Number of tasks currently running",
    unit="{task}",
)

# Histogram: Duration of the entire job execution
JOB_EXECUTION_DURATION = meter.create_histogram(
    name="agentdist.job.execution_duration",
    description="Duration of the entire job execution",
    unit="s",
)

# Counter: Count of job executions (success/failure)
JOB_EXECUTION_COUNT = meter.create_counter(
    name="agentdist.job.execution_count",
    description="Count of job executions",
    unit="{job}",
)

# Histogram: Duration of a stage execution
STAGE_EXECUTION_DURATION = meter.create_histogram(
    name="agentdist.stage.execution_duration",
    description="Duration of a stage execution",
    unit="s",
)

# Histogram: Duration of stage environment teardown
STAGE_ENV_TEARDOWN_DURATION = meter.create_histogram(
    name="agentdist.stage.env_teardown_duration",
    description="Duration of stage environment teardown",
    unit="s",
)

# Token Counter: Count of tokens generated by LLMs during agent execution
OUTPUT_TOKEN_COUNTER = meter.create_counter(
    name="agent.llm.output_tokens",
    description="Total number of tokens generated",
    unit="tokens"
)
# No. of input tasks for the operations
NO_OF_INPUT_TASKS = meter.create_counter(
    name="agentdist.job.no_of_input_tasks",
    description="Total number of input tasks for a job",
    unit="{task}"
)