"""Connector phrases placed between sections of the final document, and the
file-extension -> markdown language map used for code fences."""

TREE = [
    "Let me start by looking at the repository structure to understand the codebase.",
    "First, I'll explore the repository structure.",
    "Let me check the files in the repository.",
    "I'll begin by examining the project layout.",
    "Here's the repository structure for reference:",
    "Let me take a look at how this project is organized.",
    "First, let me see what files are in this repository.",
    "Let me get an overview of the project structure.",
    "I'll map out the repository first.",
    "Quick look at the project layout:",
    "Let me see what we're working with here.",
    "Starting with a survey of the codebase.",
    "Repository layout, for context:",
    "Let me orient myself with the file tree.",
    "Checking the project structure first.",
    "Here is the file tree:",
    "Project structure:",
    "Let me list the files in this repo.",
    "I want to understand the layout before diving in.",
    "Let me get the lay of the land.",
]

BASE_FILES = [
    "Now let me look at the existing source code that will be modified.",
    "Let me examine the relevant files before making changes.",
    "I'll review the current state of the files that need to be updated.",
    "Here are the files I'll be working with:",
    "Let me read through the relevant source files.",
    "Let me check the current contents of the files involved.",
    "Now I need to look at the files that will be changed.",
    "I'll start by reading the files that need modification.",
    "Pulling up the files that need attention:",
    "Let me load the relevant files into context.",
    "Reading the existing implementation first:",
    "Time to look at what's currently in these files.",
    "Let me see the current code before I touch it.",
    "Here are the relevant files as they exist today:",
    "Let me get the current state of the affected files.",
    "I'll review the code I need to modify first.",
    "Opening the files I need to edit:",
    "The current implementation looks like this:",
    "Let me check what's there now.",
    "Before editing, let me read the files:",
]

BASE_FILE_INLINE = [
    "Let me look at this file first:",
    "I need to read this file:",
    "Pulling up the file I'll be editing:",
    "Here's the current content:",
    "Let me check what's currently there:",
    "Current state of the file:",
    "Looking at the file before editing:",
    "Let me see the existing implementation:",
    "Before editing, the file looks like:",
    "Reading the file first:",
    "Let me load this file:",
    "Existing content for context:",
    "The current code:",
    "Here's what we have today:",
]

FIRST_COMMIT = [
    "Now I'll start implementing the changes.",
    "Let me begin making the necessary changes.",
    "Time to start working on this.",
    "I'll begin implementing this now.",
    "Let me start with the first set of changes.",
    "Now let me work through the implementation.",
    "Alright, let me start coding this up.",
    "Let me get started on the implementation.",
    "Starting with the actual edits now.",
    "Let me dive in.",
    "Okay, time to make the changes.",
    "Let me start editing.",
    "Now to apply the fix.",
    "Let me get to work.",
    "Beginning the changes:",
    "Here we go.",
    "Let me start making edits.",
    "Time to write the code.",
    "Let me apply the first change.",
    "Now for the implementation:",
]

NEXT_COMMIT = [
    "Moving on to the next change.",
    "Next, I need to handle the following.",
    "Continuing with the next set of changes.",
    "Now for the next part.",
    "Let me continue with the next modification.",
    "Next up:",
    "On to the next step.",
    "Now I'll tackle the next piece.",
    "Let me move on to the next file.",
    "There's another change needed.",
    "Alright, next I need to address this.",
    "The next thing to handle is the following.",
    "Now let me turn to the next part of this.",
    "Proceeding to the next change.",
    "Let me handle the next part now.",
    "Here's the next change that's needed.",
    "Next commit:",
    "Moving forward.",
    "On to the next bit.",
    "Continuing.",
    "Now the next part:",
    "Let me follow up with the next change.",
    "Next edit:",
    "Now for the second change.",
    "Pivoting to the next file.",
    "Onward to the next change.",
]

FINAL_OUTPUT = [
    "Here's the complete set of changes:",
    "Let me present the final result.",
    "Here's a summary of all the changes made:",
    "Here is the full diff of all modifications:",
    "Now let me show the combined result of all the changes.",
    "Putting it all together, here's the final diff:",
    "The complete patch:",
    "All changes combined:",
    "Final diff across everything:",
    "Here is everything together:",
    "Combined view of the changes:",
    "Full set of edits:",
    "The complete change set:",
    "Putting all the pieces together:",
]

SUMMARY = [
    "To summarize what was done:",
    "In summary:",
    "To wrap up:",
    "Here's a summary of the changes:",
    "Recapping the work:",
    "Summary of the changes:",
    "To recap:",
    "Wrapping up:",
    "In short:",
    "Summary:",
]

MD_LANGUAGE = {
    "py": "python", "pyi": "python", "pyx": "python",
    "js": "javascript", "mjs": "javascript", "cjs": "javascript", "jsx": "jsx",
    "ts": "typescript", "tsx": "tsx",
    "java": "java", "kt": "kotlin", "kts": "kotlin", "scala": "scala",
    "go": "go", "rs": "rust",
    "c": "c", "h": "c", "cpp": "cpp", "cc": "cpp", "cxx": "cpp", "hpp": "cpp", "hxx": "cpp", "hh": "cpp",
    "cs": "csharp", "rb": "ruby", "erb": "ruby", "php": "php", "swift": "swift",
    "m": "objectivec", "mm": "objectivec", "r": "r", "jl": "julia", "lua": "lua",
    "pl": "perl", "pm": "perl", "hs": "haskell", "ex": "elixir", "exs": "elixir", "erl": "erlang",
    "clj": "clojure", "cljs": "clojure", "cljc": "clojure", "dart": "dart", "zig": "zig", "v": "v",
    "nim": "nim", "ml": "ocaml", "mli": "ocaml", "fs": "fsharp", "fsx": "fsharp",
    "sh": "bash", "bash": "bash", "zsh": "bash", "ksh": "bash", "ps1": "powershell",
    "yaml": "yaml", "yml": "yaml", "json": "json", "toml": "toml", "xml": "xml",
    "html": "html", "htm": "html", "css": "css", "scss": "scss", "sass": "sass", "less": "less",
    "md": "markdown", "markdown": "markdown", "sql": "sql", "tf": "terraform", "hcl": "hcl",
    "proto": "protobuf", "graphql": "graphql", "gql": "graphql", "vue": "vue", "svelte": "svelte",
    "tex": "latex", "rst": "rst", "ipynb": "json", "dockerfile": "dockerfile", "makefile": "makefile",
    "mk": "makefile", "cmake": "cmake", "groovy": "groovy", "gradle": "groovy",
}
